/*
MIT License

Copyright (c) 2019 Michel Dénommée

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#ifndef _libevmvc_utils_h
#define _libevmvc_utils_h

#include "stable_headers.h"




namespace evmvc {

inline std::string html_version()
{
    static std::string ver =
        md::replace_substring_copy(
            md::replace_substring_copy(version(), "\n", "<br/>"),
            " ", "&nbsp;"
        );
    return ver;
}



template<typename PARAM_T>
PARAM_T json_default(
    const evmvc::json& jobj,
    md::string_view key,
    PARAM_T def_val)
{
    auto it = jobj.find(key.to_string());
    if(it == jobj.end())
        return def_val;
    if(it->is_null())
        return def_val;
    return *it;
}


inline evmvc::json parse_jsonc_string(const std::string jsonwc)
{
    bool in_str = false;
    // single line comments
    bool in_scom = false;
    // multi line comments
    bool in_mcom = false;
    
    ssize_t last_comma_loc = -1;
    
    std::string res;
    // removes comments
    for(size_t i = 0; i < jsonwc.size(); ++i){
        //char pprev_chr = i > 1 ? jsonwc[i-2] : 0;
        char prev_chr = i > 0 ? jsonwc[i-1] : 0;
        char cur_chr = jsonwc[i];
        char nxt_chr = i < jsonwc.size()-1 ? jsonwc[i+1] : 0;
        
        if(in_scom){
            if(cur_chr == '\n'){
                in_scom = false;
                if(prev_chr == '\r')
                    res += '\r';
                res += '\n';
            }
            continue;
        }
        
        if(in_mcom){
            if(cur_chr == '/' && prev_chr == '*'){
                in_mcom = false;
                
            }else if(cur_chr == '\n'){
                if(prev_chr == '\r')
                    res += '\r';
                res += '\n';
            }
            
            continue;
        }
        
        if(in_str){
            if(cur_chr == '\\'){
                if(nxt_chr != 0){
                    res += cur_chr;
                    res += nxt_chr;
                    ++i;
                    continue;
                }
                throw MD_ERR("JSONC invalid format!");
            }
            
            if(cur_chr == '"')
                in_str = false;
            res += cur_chr;
            continue;
        }
        
        if(cur_chr == '/' && nxt_chr == '/'){
            in_scom = true;
            continue;
        }
        
        if(cur_chr == '/' && nxt_chr == '*'){
            in_mcom = true;
            continue;
        }
        
        if(cur_chr == '"'){
            last_comma_loc = -1;
            in_str = true;
            res += cur_chr;
            continue;
        }
        
        //verify if it's a bad comma
        if(cur_chr == '}' || cur_chr == ']'){
            if(last_comma_loc > -1){
                std::string tmp = res.substr(0, last_comma_loc);
                if((size_t)(last_comma_loc+1) < res.size())
                    tmp += res.substr(last_comma_loc+1);
                res = tmp;
            }
            last_comma_loc = -1;
        }
        if(cur_chr == ','){
            last_comma_loc = res.size();
        }else if(last_comma_loc > -1 && !isspace(cur_chr) &&
            cur_chr != '\t' && cur_chr != '\n' && cur_chr != '\r'
        ){
            last_comma_loc = -1;
        }
        
        res += cur_chr;
    }
    
    return evmvc::json::parse(res);
}
inline evmvc::json parse_jsonc_file(
    const md::string_view jsonc_filename)
{
    std::ifstream fin(
        jsonc_filename.data(), std::ios::binary
    );
    std::ostringstream ostrm;
    ostrm << fin.rdbuf();
    std::string jsonwc = ostrm.str();
    fin.close();
    return parse_jsonc_string(jsonwc);
}


inline std::string data_substring(
    const char* data, size_t offset, size_t end_idx)
{
    return std::string(data+offset, end_idx-offset);
}

inline std::string data_substr(
    const char* data, size_t offset, size_t len)
{
    return std::string(data+offset, len);
}

inline ssize_t find_ch(
    const char* data, size_t len, char ch, size_t start_pos)
{
    for(size_t i = start_pos; i < len; ++i)
        if(data[i] == ch)
            return i;
    return -1;
}

inline ssize_t find_eol(const char* data, size_t len, size_t start_pos)
{
    for(size_t i = start_pos; i < len -1; ++i)
        if(data[i] == '\r' && data[i+1] == '\n')
            return i;
    return -1;
}

inline std::string escape(md::string_view s)
{
    char* r = evhttp_encode_uri(s.data());
    std::string tmp(r);
    free(r);
    return tmp;
}
inline std::string unescape(md::string_view s)
{
    char* r = evhttp_decode_uri(s.data());
    std::string tmp(r);
    free(r);
    return tmp;
}
inline std::string html_escape(md::string_view s)
{
    char* r = evhttp_htmlescape(s.data());
    std::string tmp(r);
    free(r);
    return tmp;
}
inline std::string html_unescape(md::string_view s)
{
    static std::unordered_map<std::string, std::string> html_entities = {
        {"Aacute", "\u00c1"},
        {"aacute", "\u00e1"},
        {"Abreve", "\u0102"},
        {"abreve", "\u0103"},
        {"ac", "\u223e"},
        {"acd", "\u223f"},
        {"acE", "\u223e\u0333"},
        {"Acirc", "\u00c2"},
        {"acirc", "\u00e2"},
        {"acute", "\u00b4"},
        {"Acy", "\u0410"},
        {"acy", "\u0430"},
        {"AElig", "\u00c6"},
        {"aelig", "\u00e6"},
        {"af", "\u2061"},
        {"Afr", "\U0001D504"},
        {"afr", "\U0001D51E"},
        {"Agrave", "\u00c0"},
        {"agrave", "\u00e0"},
        {"alefsym", "\u2135"},
        {"aleph", "\u2135"},
        {"Alpha", "\u0391"},
        {"alpha", "\u03b1"},
        {"Amacr", "\u0100"},
        {"amacr", "\u0101"},
        {"amalg", "\u2a3f"},
        {"AMP", "\u0026"},
        {"amp", "\u0026"},
        {"And", "\u2a53"},
        {"and", "\u2227"},
        {"andand", "\u2a55"},
        {"andd", "\u2a5c"},
        {"andslope", "\u2a58"},
        {"andv", "\u2a5a"},
        {"ang", "\u2220"},
        {"ange", "\u29a4"},
        {"angle", "\u2220"},
        {"angmsd", "\u2221"},
        {"angmsdaa", "\u29a8"},
        {"angmsdab", "\u29a9"},
        {"angmsdac", "\u29aa"},
        {"angmsdad", "\u29ab"},
        {"angmsdae", "\u29ac"},
        {"angmsdaf", "\u29ad"},
        {"angmsdag", "\u29ae"},
        {"angmsdah", "\u29af"},
        {"angrt", "\u221f"},
        {"angrtvb", "\u22be"},
        {"angrtvbd", "\u299d"},
        {"angsph", "\u2222"},
        {"angst", "\u00c5"},
        {"angzarr", "\u237c"},
        {"Aogon", "\u0104"},
        {"aogon", "\u0105"},
        {"Aopf", "\U0001D538"},
        {"aopf", "\U0001D552"},
        {"ap", "\u2248"},
        {"apacir", "\u2a6f"},
        {"apE", "\u2a70"},
        {"ape", "\u224a"},
        {"apid", "\u224b"},
        {"apos", "\u0027"},
        {"ApplyFunction", "\u2061"},
        {"approx", "\u2248"},
        {"approxeq", "\u224a"},
        {"Aring", "\u00c5"},
        {"aring", "\u00e5"},
        {"Ascr", "\U0001D49C"},
        {"ascr", "\U0001D4B6"},
        {"Assign", "\u2254"},
        {"ast", "\u002a"},
        {"asymp", "\u2248"},
        {"asympeq", "\u224d"},
        {"Atilde", "\u00c3"},
        {"atilde", "\u00e3"},
        {"Auml", "\u00c4"},
        {"auml", "\u00e4"},
        {"awconint", "\u2233"},
        {"awint", "\u2a11"},
        {"backcong", "\u224c"},
        {"backepsilon", "\u03f6"},
        {"backprime", "\u2035"},
        {"backsim", "\u223d"},
        {"backsimeq", "\u22cd"},
        {"Backslash", "\u2216"},
        {"Barv", "\u2ae7"},
        {"barvee", "\u22bd"},
        {"Barwed", "\u2306"},
        {"barwed", "\u2305"},
        {"barwedge", "\u2305"},
        {"bbrk", "\u23b5"},
        {"bbrktbrk", "\u23b6"},
        {"bcong", "\u224c"},
        {"Bcy", "\u0411"},
        {"bcy", "\u0431"},
        {"bdquo", "\u201e"},
        {"becaus", "\u2235"},
        {"Because", "\u2235"},
        {"because", "\u2235"},
        {"bemptyv", "\u29b0"},
        {"bepsi", "\u03f6"},
        {"bernou", "\u212c"},
        {"Bernoullis", "\u212c"},
        {"Beta", "\u0392"},
        {"beta", "\u03b2"},
        {"beth", "\u2136"},
        {"between", "\u226c"},
        {"Bfr", "\U0001D505"},
        {"bfr", "\U0001D51F"},
        {"bigcap", "\u22c2"},
        {"bigcirc", "\u25ef"},
        {"bigcup", "\u22c3"},
        {"bigodot", "\u2a00"},
        {"bigoplus", "\u2a01"},
        {"bigotimes", "\u2a02"},
        {"bigsqcup", "\u2a06"},
        {"bigstar", "\u2605"},
        {"bigtriangledown", "\u25bd"},
        {"bigtriangleup", "\u25b3"},
        {"biguplus", "\u2a04"},
        {"bigvee", "\u22c1"},
        {"bigwedge", "\u22c0"},
        {"bkarow", "\u290d"},
        {"blacklozenge", "\u29eb"},
        {"blacksquare", "\u25aa"},
        {"blacktriangle", "\u25b4"},
        {"blacktriangledown", "\u25be"},
        {"blacktriangleleft", "\u25c2"},
        {"blacktriangleright", "\u25b8"},
        {"blank", "\u2423"},
        {"blk12", "\u2592"},
        {"blk14", "\u2591"},
        {"blk34", "\u2593"},
        {"block", "\u2588"},
        {"bne", "\u003d\u20e5"},
        {"bnequiv", "\u2261\u20e5"},
        {"bNot", "\u2aed"},
        {"bnot", "\u2310"},
        {"Bopf", "\U0001D539"},
        {"bopf", "\U0001D553"},
        {"bot", "\u22a5"},
        {"bottom", "\u22a5"},
        {"bowtie", "\u22c8"},
        {"boxbox", "\u29c9"},
        {"boxDL", "\u2557"},
        {"boxDl", "\u2556"},
        {"boxdL", "\u2555"},
        {"boxdl", "\u2510"},
        {"boxDR", "\u2554"},
        {"boxDr", "\u2553"},
        {"boxdR", "\u2552"},
        {"boxdr", "\u250c"},
        {"boxH", "\u2550"},
        {"boxh", "\u2500"},
        {"boxHD", "\u2566"},
        {"boxHd", "\u2564"},
        {"boxhD", "\u2565"},
        {"boxhd", "\u252c"},
        {"boxHU", "\u2569"},
        {"boxHu", "\u2567"},
        {"boxhU", "\u2568"},
        {"boxhu", "\u2534"},
        {"boxminus", "\u229f"},
        {"boxplus", "\u229e"},
        {"boxtimes", "\u22a0"},
        {"boxUL", "\u255d"},
        {"boxUl", "\u255c"},
        {"boxuL", "\u255b"},
        {"boxul", "\u2518"},
        {"boxUR", "\u255a"},
        {"boxUr", "\u2559"},
        {"boxuR", "\u2558"},
        {"boxur", "\u2514"},
        {"boxV", "\u2551"},
        {"boxv", "\u2502"},
        {"boxVH", "\u256c"},
        {"boxVh", "\u256b"},
        {"boxvH", "\u256a"},
        {"boxvh", "\u253c"},
        {"boxVL", "\u2563"},
        {"boxVl", "\u2562"},
        {"boxvL", "\u2561"},
        {"boxvl", "\u2524"},
        {"boxVR", "\u2560"},
        {"boxVr", "\u255f"},
        {"boxvR", "\u255e"},
        {"boxvr", "\u251c"},
        {"bprime", "\u2035"},
        {"Breve", "\u02d8"},
        {"breve", "\u02d8"},
        {"brvbar", "\u00a6"},
        {"Bscr", "\u212c"},
        {"bscr", "\U0001D4B7"},
        {"bsemi", "\u204f"},
        {"bsim", "\u223d"},
        {"bsime", "\u22cd"},
        {"bsol", "\u005c"},
        {"bsolb", "\u29c5"},
        {"bsolhsub", "\u27c8"},
        {"bull", "\u2022"},
        {"bullet", "\u2022"},
        {"bump", "\u224e"},
        {"bumpE", "\u2aae"},
        {"bumpe", "\u224f"},
        {"Bumpeq", "\u224e"},
        {"bumpeq", "\u224f"},
        {"Cacute", "\u0106"},
        {"cacute", "\u0107"},
        {"Cap", "\u22d2"},
        {"cap", "\u2229"},
        {"capand", "\u2a44"},
        {"capbrcup", "\u2a49"},
        {"capcap", "\u2a4b"},
        {"capcup", "\u2a47"},
        {"capdot", "\u2a40"},
        {"CapitalDifferentialD", "\u2145"},
        {"caps", "\u2229\ufe00"},
        {"caret", "\u2041"},
        {"caron", "\u02c7"},
        {"Cayleys", "\u212d"},
        {"ccaps", "\u2a4d"},
        {"Ccaron", "\u010c"},
        {"ccaron", "\u010d"},
        {"Ccedil", "\u00c7"},
        {"ccedil", "\u00e7"},
        {"Ccirc", "\u0108"},
        {"ccirc", "\u0109"},
        {"Cconint", "\u2230"},
        {"ccups", "\u2a4c"},
        {"ccupssm", "\u2a50"},
        {"Cdot", "\u010a"},
        {"cdot", "\u010b"},
        {"cedil", "\u00b8"},
        {"Cedilla", "\u00b8"},
        {"cemptyv", "\u29b2"},
        {"cent", "\u00a2"},
        {"CenterDot", "\u00b7"},
        {"centerdot", "\u00b7"},
        {"Cfr", "\u212d"},
        {"cfr", "\U0001D520"},
        {"CHcy", "\u0427"},
        {"chcy", "\u0447"},
        {"check", "\u2713"},
        {"checkmark", "\u2713"},
        {"Chi", "\u03a7"},
        {"chi", "\u03c7"},
        {"cir", "\u25cb"},
        {"circ", "\u02c6"},
        {"circeq", "\u2257"},
        {"circlearrowleft", "\u21ba"},
        {"circlearrowright", "\u21bb"},
        {"circledast", "\u229b"},
        {"circledcirc", "\u229a"},
        {"circleddash", "\u229d"},
        {"CircleDot", "\u2299"},
        {"circledR", "\u00ae"},
        {"circledS", "\u24c8"},
        {"CircleMinus", "\u2296"},
        {"CirclePlus", "\u2295"},
        {"CircleTimes", "\u2297"},
        {"cirE", "\u29c3"},
        {"cire", "\u2257"},
        {"cirfnint", "\u2a10"},
        {"cirmid", "\u2aef"},
        {"cirscir", "\u29c2"},
        {"ClockwiseContourIntegral", "\u2232"},
        {"CloseCurlyDoubleQuote", "\u201d"},
        {"CloseCurlyQuote", "\u2019"},
        {"clubs", "\u2663"},
        {"clubsuit", "\u2663"},
        {"Colon", "\u2237"},
        {"colon", "\u003a"},
        {"Colone", "\u2a74"},
        {"colone", "\u2254"},
        {"coloneq", "\u2254"},
        {"comma", "\u002c"},
        {"commat", "\u0040"},
        {"comp", "\u2201"},
        {"compfn", "\u2218"},
        {"complement", "\u2201"},
        {"complexes", "\u2102"},
        {"cong", "\u2245"},
        {"congdot", "\u2a6d"},
        {"Congruent", "\u2261"},
        {"Conint", "\u222f"},
        {"conint", "\u222e"},
        {"ContourIntegral", "\u222e"},
        {"Copf", "\u2102"},
        {"copf", "\U0001D554"},
        {"coprod", "\u2210"},
        {"Coproduct", "\u2210"},
        {"COPY", "\u00a9"},
        {"copy", "\u00a9"},
        {"copysr", "\u2117"},
        {"CounterClockwiseContourIntegral", "\u2233"},
        {"crarr", "\u21b5"},
        {"Cross", "\u2a2f"},
        {"cross", "\u2717"},
        {"Cscr", "\U0001D49E"},
        {"cscr", "\U0001D4B8"},
        {"csub", "\u2acf"},
        {"csube", "\u2ad1"},
        {"csup", "\u2ad0"},
        {"csupe", "\u2ad2"},
        {"ctdot", "\u22ef"},
        {"cudarrl", "\u2938"},
        {"cudarrr", "\u2935"},
        {"cuepr", "\u22de"},
        {"cuesc", "\u22df"},
        {"cularr", "\u21b6"},
        {"cularrp", "\u293d"},
        {"Cup", "\u22d3"},
        {"cup", "\u222a"},
        {"cupbrcap", "\u2a48"},
        {"CupCap", "\u224d"},
        {"cupcap", "\u2a46"},
        {"cupcup", "\u2a4a"},
        {"cupdot", "\u228d"},
        {"cupor", "\u2a45"},
        {"cups", "\u222a\ufe00"},
        {"curarr", "\u21b7"},
        {"curarrm", "\u293c"},
        {"curlyeqprec", "\u22de"},
        {"curlyeqsucc", "\u22df"},
        {"curlyvee", "\u22ce"},
        {"curlywedge", "\u22cf"},
        {"curren", "\u00a4"},
        {"curvearrowleft", "\u21b6"},
        {"curvearrowright", "\u21b7"},
        {"cuvee", "\u22ce"},
        {"cuwed", "\u22cf"},
        {"cwconint", "\u2232"},
        {"cwint", "\u2231"},
        {"cylcty", "\u232d"},
        {"Dagger", "\u2021"},
        {"dagger", "\u2020"},
        {"daleth", "\u2138"},
        {"Darr", "\u21a1"},
        {"dArr", "\u21d3"},
        {"darr", "\u2193"},
        {"dash", "\u2010"},
        {"Dashv", "\u2ae4"},
        {"dashv", "\u22a3"},
        {"dbkarow", "\u290f"},
        {"dblac", "\u02dd"},
        {"Dcaron", "\u010e"},
        {"dcaron", "\u010f"},
        {"Dcy", "\u0414"},
        {"dcy", "\u0434"},
        {"DD", "\u2145"},
        {"dd", "\u2146"},
        {"ddagger", "\u2021"},
        {"ddarr", "\u21ca"},
        {"DDotrahd", "\u2911"},
        {"ddotseq", "\u2a77"},
        {"deg", "\u00b0"},
        {"Del", "\u2207"},
        {"Delta", "\u0394"},
        {"delta", "\u03b4"},
        {"demptyv", "\u29b1"},
        {"dfisht", "\u297f"},
        {"Dfr", "\U0001D507"},
        {"dfr", "\U0001D521"},
        {"dHar", "\u2965"},
        {"dharl", "\u21c3"},
        {"dharr", "\u21c2"},
        {"DiacriticalAcute", "\u00b4"},
        {"DiacriticalDot", "\u02d9"},
        {"DiacriticalDoubleAcute", "\u02dd"},
        {"DiacriticalGrave", "\u0060"},
        {"DiacriticalTilde", "\u02dc"},
        {"diam", "\u22c4"},
        {"Diamond", "\u22c4"},
        {"diamond", "\u22c4"},
        {"diamondsuit", "\u2666"},
        {"diams", "\u2666"},
        {"die", "\u00a8"},
        {"DifferentialD", "\u2146"},
        {"digamma", "\u03dd"},
        {"disin", "\u22f2"},
        {"div", "\u00f7"},
        {"divide", "\u00f7"},
        {"divideontimes", "\u22c7"},
        {"divonx", "\u22c7"},
        {"DJcy", "\u0402"},
        {"djcy", "\u0452"},
        {"dlcorn", "\u231e"},
        {"dlcrop", "\u230d"},
        {"dollar", "\u0024"},
        {"Dopf", "\U0001D53B"},
        {"dopf", "\U0001D555"},
        {"Dot", "\u00a8"},
        {"dot", "\u02d9"},
        {"DotDot", "\u20dc"},
        {"doteq", "\u2250"},
        {"doteqdot", "\u2251"},
        {"DotEqual", "\u2250"},
        {"dotminus", "\u2238"},
        {"dotplus", "\u2214"},
        {"dotsquare", "\u22a1"},
        {"doublebarwedge", "\u2306"},
        {"DoubleContourIntegral", "\u222f"},
        {"DoubleDot", "\u00a8"},
        {"DoubleDownArrow", "\u21d3"},
        {"DoubleLeftArrow", "\u21d0"},
        {"DoubleLeftRightArrow", "\u21d4"},
        {"DoubleLeftTee", "\u2ae4"},
        {"DoubleLongLeftArrow", "\u27f8"},
        {"DoubleLongLeftRightArrow", "\u27fa"},
        {"DoubleLongRightArrow", "\u27f9"},
        {"DoubleRightArrow", "\u21d2"},
        {"DoubleRightTee", "\u22a8"},
        {"DoubleUpArrow", "\u21d1"},
        {"DoubleUpDownArrow", "\u21d5"},
        {"DoubleVerticalBar", "\u2225"},
        {"DownArrow", "\u2193"},
        {"Downarrow", "\u21d3"},
        {"downarrow", "\u2193"},
        {"DownArrowBar", "\u2913"},
        {"DownArrowUpArrow", "\u21f5"},
        {"DownBreve", "\u0311"},
        {"downdownarrows", "\u21ca"},
        {"downharpoonleft", "\u21c3"},
        {"downharpoonright", "\u21c2"},
        {"DownLeftRightVector", "\u2950"},
        {"DownLeftTeeVector", "\u295e"},
        {"DownLeftVector", "\u21bd"},
        {"DownLeftVectorBar", "\u2956"},
        {"DownRightTeeVector", "\u295f"},
        {"DownRightVector", "\u21c1"},
        {"DownRightVectorBar", "\u2957"},
        {"DownTee", "\u22a4"},
        {"DownTeeArrow", "\u21a7"},
        {"drbkarow", "\u2910"},
        {"drcorn", "\u231f"},
        {"drcrop", "\u230c"},
        {"Dscr", "\U0001D49F"},
        {"dscr", "\U0001D4B9"},
        {"DScy", "\u0405"},
        {"dscy", "\u0455"},
        {"dsol", "\u29f6"},
        {"Dstrok", "\u0110"},
        {"dstrok", "\u0111"},
        {"dtdot", "\u22f1"},
        {"dtri", "\u25bf"},
        {"dtrif", "\u25be"},
        {"duarr", "\u21f5"},
        {"duhar", "\u296f"},
        {"dwangle", "\u29a6"},
        {"DZcy", "\u040f"},
        {"dzcy", "\u045f"},
        {"dzigrarr", "\u27ff"},
        {"Eacute", "\u00c9"},
        {"eacute", "\u00e9"},
        {"easter", "\u2a6e"},
        {"Ecaron", "\u011a"},
        {"ecaron", "\u011b"},
        {"ecir", "\u2256"},
        {"Ecirc", "\u00ca"},
        {"ecirc", "\u00ea"},
        {"ecolon", "\u2255"},
        {"Ecy", "\u042d"},
        {"ecy", "\u044d"},
        {"eDDot", "\u2a77"},
        {"Edot", "\u0116"},
        {"eDot", "\u2251"},
        {"edot", "\u0117"},
        {"ee", "\u2147"},
        {"efDot", "\u2252"},
        {"Efr", "\U0001D508"},
        {"efr", "\U0001D522"},
        {"eg", "\u2a9a"},
        {"Egrave", "\u00c8"},
        {"egrave", "\u00e8"},
        {"egs", "\u2a96"},
        {"egsdot", "\u2a98"},
        {"el", "\u2a99"},
        {"Element", "\u2208"},
        {"elinters", "\u23e7"},
        {"ell", "\u2113"},
        {"els", "\u2a95"},
        {"elsdot", "\u2a97"},
        {"Emacr", "\u0112"},
        {"emacr", "\u0113"},
        {"empty", "\u2205"},
        {"emptyset", "\u2205"},
        {"EmptySmallSquare", "\u25fb"},
        {"emptyv", "\u2205"},
        {"EmptyVerySmallSquare", "\u25ab"},
        {"emsp", "\u2003"},
        {"emsp13", "\u2004"},
        {"emsp14", "\u2005"},
        {"ENG", "\u014a"},
        {"eng", "\u014b"},
        {"ensp", "\u2002"},
        {"Eogon", "\u0118"},
        {"eogon", "\u0119"},
        {"Eopf", "\U0001D53C"},
        {"eopf", "\U0001D556"},
        {"epar", "\u22d5"},
        {"eparsl", "\u29e3"},
        {"eplus", "\u2a71"},
        {"epsi", "\u03b5"},
        {"Epsilon", "\u0395"},
        {"epsilon", "\u03b5"},
        {"epsiv", "\u03f5"},
        {"eqcirc", "\u2256"},
        {"eqcolon", "\u2255"},
        {"eqsim", "\u2242"},
        {"eqslantgtr", "\u2a96"},
        {"eqslantless", "\u2a95"},
        {"Equal", "\u2a75"},
        {"equals", "\u003d"},
        {"EqualTilde", "\u2242"},
        {"equest", "\u225f"},
        {"Equilibrium", "\u21cc"},
        {"equiv", "\u2261"},
        {"equivDD", "\u2a78"},
        {"eqvparsl", "\u29e5"},
        {"erarr", "\u2971"},
        {"erDot", "\u2253"},
        {"Escr", "\u2130"},
        {"escr", "\u212f"},
        {"esdot", "\u2250"},
        {"Esim", "\u2a73"},
        {"esim", "\u2242"},
        {"Eta", "\u0397"},
        {"eta", "\u03b7"},
        {"ETH", "\u00d0"},
        {"eth", "\u00f0"},
        {"Euml", "\u00cb"},
        {"euml", "\u00eb"},
        {"euro", "\u20ac"},
        {"excl", "\u0021"},
        {"exist", "\u2203"},
        {"Exists", "\u2203"},
        {"expectation", "\u2130"},
        {"ExponentialE", "\u2147"},
        {"exponentiale", "\u2147"},
        {"fallingdotseq", "\u2252"},
        {"Fcy", "\u0424"},
        {"fcy", "\u0444"},
        {"female", "\u2640"},
        {"ffilig", "\ufb03"},
        {"fflig", "\ufb00"},
        {"ffllig", "\ufb04"},
        {"Ffr", "\U0001D509"},
        {"ffr", "\U0001D523"},
        {"filig", "\ufb01"},
        {"FilledSmallSquare", "\u25fc"},
        {"FilledVerySmallSquare", "\u25aa"},
        {"fjlig", "\u0066\u006a"},
        {"flat", "\u266d"},
        {"fllig", "\ufb02"},
        {"fltns", "\u25b1"},
        {"fnof", "\u0192"},
        {"Fopf", "\U0001D53D"},
        {"fopf", "\U0001D557"},
        {"ForAll", "\u2200"},
        {"forall", "\u2200"},
        {"fork", "\u22d4"},
        {"forkv", "\u2ad9"},
        {"Fouriertrf", "\u2131"},
        {"fpartint", "\u2a0d"},
        {"frac12", "\u00bd"},
        {"frac13", "\u2153"},
        {"frac14", "\u00bc"},
        {"frac15", "\u2155"},
        {"frac16", "\u2159"},
        {"frac18", "\u215b"},
        {"frac23", "\u2154"},
        {"frac25", "\u2156"},
        {"frac34", "\u00be"},
        {"frac35", "\u2157"},
        {"frac38", "\u215c"},
        {"frac45", "\u2158"},
        {"frac56", "\u215a"},
        {"frac58", "\u215d"},
        {"frac78", "\u215e"},
        {"frasl", "\u2044"},
        {"frown", "\u2322"},
        {"Fscr", "\u2131"},
        {"fscr", "\U0001D4BB"},
        {"gacute", "\u01f5"},
        {"Gamma", "\u0393"},
        {"gamma", "\u03b3"},
        {"Gammad", "\u03dc"},
        {"gammad", "\u03dd"},
        {"gap", "\u2a86"},
        {"Gbreve", "\u011e"},
        {"gbreve", "\u011f"},
        {"Gcedil", "\u0122"},
        {"Gcirc", "\u011c"},
        {"gcirc", "\u011d"},
        {"Gcy", "\u0413"},
        {"gcy", "\u0433"},
        {"Gdot", "\u0120"},
        {"gdot", "\u0121"},
        {"gE", "\u2267"},
        {"ge", "\u2265"},
        {"gEl", "\u2a8c"},
        {"gel", "\u22db"},
        {"geq", "\u2265"},
        {"geqq", "\u2267"},
        {"geqslant", "\u2a7e"},
        {"ges", "\u2a7e"},
        {"gescc", "\u2aa9"},
        {"gesdot", "\u2a80"},
        {"gesdoto", "\u2a82"},
        {"gesdotol", "\u2a84"},
        {"gesl", "\u22db\ufe00"},
        {"gesles", "\u2a94"},
        {"Gfr", "\U0001D50A"},
        {"gfr", "\U0001D524"},
        {"Gg", "\u22d9"},
        {"gg", "\u226b"},
        {"ggg", "\u22d9"},
        {"gimel", "\u2137"},
        {"GJcy", "\u0403"},
        {"gjcy", "\u0453"},
        {"gl", "\u2277"},
        {"gla", "\u2aa5"},
        {"glE", "\u2a92"},
        {"glj", "\u2aa4"},
        {"gnap", "\u2a8a"},
        {"gnapprox", "\u2a8a"},
        {"gnE", "\u2269"},
        {"gne", "\u2a88"},
        {"gneq", "\u2a88"},
        {"gneqq", "\u2269"},
        {"gnsim", "\u22e7"},
        {"Gopf", "\U0001D53E"},
        {"gopf", "\U0001D558"},
        {"grave", "\u0060"},
        {"GreaterEqual", "\u2265"},
        {"GreaterEqualLess", "\u22db"},
        {"GreaterFullEqual", "\u2267"},
        {"GreaterGreater", "\u2aa2"},
        {"GreaterLess", "\u2277"},
        {"GreaterSlantEqual", "\u2a7e"},
        {"GreaterTilde", "\u2273"},
        {"Gscr", "\U0001D4A2"},
        {"gscr", "\u210a"},
        {"gsim", "\u2273"},
        {"gsime", "\u2a8e"},
        {"gsiml", "\u2a90"},
        {"GT", "\u003e"},
        {"Gt", "\u226b"},
        {"gt", "\u003e"},
        {"gtcc", "\u2aa7"},
        {"gtcir", "\u2a7a"},
        {"gtdot", "\u22d7"},
        {"gtlPar", "\u2995"},
        {"gtquest", "\u2a7c"},
        {"gtrapprox", "\u2a86"},
        {"gtrarr", "\u2978"},
        {"gtrdot", "\u22d7"},
        {"gtreqless", "\u22db"},
        {"gtreqqless", "\u2a8c"},
        {"gtrless", "\u2277"},
        {"gtrsim", "\u2273"},
        {"gvertneqq", "\u2269\ufe00"},
        {"gvnE", "\u2269\ufe00"},
        {"Hacek", "\u02c7"},
        {"hairsp", "\u200a"},
        {"half", "\u00bd"},
        {"hamilt", "\u210b"},
        {"HARDcy", "\u042a"},
        {"hardcy", "\u044a"},
        {"hArr", "\u21d4"},
        {"harr", "\u2194"},
        {"harrcir", "\u2948"},
        {"harrw", "\u21ad"},
        {"Hat", "\u005e"},
        {"hbar", "\u210f"},
        {"Hcirc", "\u0124"},
        {"hcirc", "\u0125"},
        {"hearts", "\u2665"},
        {"heartsuit", "\u2665"},
        {"hellip", "\u2026"},
        {"hercon", "\u22b9"},
        {"Hfr", "\u210c"},
        {"hfr", "\U0001D525"},
        {"HilbertSpace", "\u210b"},
        {"hksearow", "\u2925"},
        {"hkswarow", "\u2926"},
        {"hoarr", "\u21ff"},
        {"homtht", "\u223b"},
        {"hookleftarrow", "\u21a9"},
        {"hookrightarrow", "\u21aa"},
        {"Hopf", "\u210d"},
        {"hopf", "\U0001D559"},
        {"horbar", "\u2015"},
        {"HorizontalLine", "\u2500"},
        {"Hscr", "\u210b"},
        {"hscr", "\U0001D4BD"},
        {"hslash", "\u210f"},
        {"Hstrok", "\u0126"},
        {"hstrok", "\u0127"},
        {"HumpDownHump", "\u224e"},
        {"HumpEqual", "\u224f"},
        {"hybull", "\u2043"},
        {"hyphen", "\u2010"},
        {"Iacute", "\u00cd"},
        {"iacute", "\u00ed"},
        {"ic", "\u2063"},
        {"Icirc", "\u00ce"},
        {"icirc", "\u00ee"},
        {"Icy", "\u0418"},
        {"icy", "\u0438"},
        {"Idot", "\u0130"},
        {"IEcy", "\u0415"},
        {"iecy", "\u0435"},
        {"iexcl", "\u00a1"},
        {"iff", "\u21d4"},
        {"Ifr", "\u2111"},
        {"ifr", "\U0001D526"},
        {"Igrave", "\u00cc"},
        {"igrave", "\u00ec"},
        {"ii", "\u2148"},
        {"iiiint", "\u2a0c"},
        {"iiint", "\u222d"},
        {"iinfin", "\u29dc"},
        {"iiota", "\u2129"},
        {"IJlig", "\u0132"},
        {"ijlig", "\u0133"},
        {"Im", "\u2111"},
        {"Imacr", "\u012a"},
        {"imacr", "\u012b"},
        {"image", "\u2111"},
        {"ImaginaryI", "\u2148"},
        {"imagline", "\u2110"},
        {"imagpart", "\u2111"},
        {"imath", "\u0131"},
        {"imof", "\u22b7"},
        {"imped", "\u01b5"},
        {"Implies", "\u21d2"},
        {"in", "\u2208"},
        {"incare", "\u2105"},
        {"infin", "\u221e"},
        {"infintie", "\u29dd"},
        {"inodot", "\u0131"},
        {"Int", "\u222c"},
        {"int", "\u222b"},
        {"intcal", "\u22ba"},
        {"integers", "\u2124"},
        {"Integral", "\u222b"},
        {"intercal", "\u22ba"},
        {"Intersection", "\u22c2"},
        {"intlarhk", "\u2a17"},
        {"intprod", "\u2a3c"},
        {"InvisibleComma", "\u2063"},
        {"InvisibleTimes", "\u2062"},
        {"IOcy", "\u0401"},
        {"iocy", "\u0451"},
        {"Iogon", "\u012e"},
        {"iogon", "\u012f"},
        {"Iopf", "\U0001D540"},
        {"iopf", "\U0001D55A"},
        {"Iota", "\u0399"},
        {"iota", "\u03b9"},
        {"iprod", "\u2a3c"},
        {"iquest", "\u00bf"},
        {"Iscr", "\u2110"},
        {"iscr", "\U0001D4BE"},
        {"isin", "\u2208"},
        {"isindot", "\u22f5"},
        {"isinE", "\u22f9"},
        {"isins", "\u22f4"},
        {"isinsv", "\u22f3"},
        {"isinv", "\u2208"},
        {"it", "\u2062"},
        {"Itilde", "\u0128"},
        {"itilde", "\u0129"},
        {"Iukcy", "\u0406"},
        {"iukcy", "\u0456"},
        {"Iuml", "\u00cf"},
        {"iuml", "\u00ef"},
        {"Jcirc", "\u0134"},
        {"jcirc", "\u0135"},
        {"Jcy", "\u0419"},
        {"jcy", "\u0439"},
        {"Jfr", "\U0001D50D"},
        {"jfr", "\U0001D527"},
        {"jmath", "\u0237"},
        {"Jopf", "\U0001D541"},
        {"jopf", "\U0001D55B"},
        {"Jscr", "\U0001D4A5"},
        {"jscr", "\U0001D4BF"},
        {"Jsercy", "\u0408"},
        {"jsercy", "\u0458"},
        {"Jukcy", "\u0404"},
        {"jukcy", "\u0454"},
        {"Kappa", "\u039a"},
        {"kappa", "\u03ba"},
        {"kappav", "\u03f0"},
        {"Kcedil", "\u0136"},
        {"kcedil", "\u0137"},
        {"Kcy", "\u041a"},
        {"kcy", "\u043a"},
        {"Kfr", "\U0001D50E"},
        {"kfr", "\U0001D528"},
        {"kgreen", "\u0138"},
        {"KHcy", "\u0425"},
        {"khcy", "\u0445"},
        {"KJcy", "\u040c"},
        {"kjcy", "\u045c"},
        {"Kopf", "\U0001D542"},
        {"kopf", "\U0001D55C"},
        {"Kscr", "\U0001D4A6"},
        {"kscr", "\U0001D4C0"},
        {"lAarr", "\u21da"},
        {"Lacute", "\u0139"},
        {"lacute", "\u013a"},
        {"laemptyv", "\u29b4"},
        {"lagran", "\u2112"},
        {"Lambda", "\u039b"},
        {"lambda", "\u03bb"},
        {"Lang", "\u27ea"},
        {"lang", "\u27e8"},
        {"langd", "\u2991"},
        {"langle", "\u27e8"},
        {"lap", "\u2a85"},
        {"Laplacetrf", "\u2112"},
        {"laquo", "\u00ab"},
        {"Larr", "\u219e"},
        {"lArr", "\u21d0"},
        {"larr", "\u2190"},
        {"larrb", "\u21e4"},
        {"larrbfs", "\u291f"},
        {"larrfs", "\u291d"},
        {"larrhk", "\u21a9"},
        {"larrlp", "\u21ab"},
        {"larrpl", "\u2939"},
        {"larrsim", "\u2973"},
        {"larrtl", "\u21a2"},
        {"lat", "\u2aab"},
        {"lAtail", "\u291b"},
        {"latail", "\u2919"},
        {"late", "\u2aad"},
        {"lates", "\u2aad\ufe00"},
        {"lBarr", "\u290e"},
        {"lbarr", "\u290c"},
        {"lbbrk", "\u2772"},
        {"lbrace", "\u007b"},
        {"lbrack", "\u005b"},
        {"lbrke", "\u298b"},
        {"lbrksld", "\u298f"},
        {"lbrkslu", "\u298d"},
        {"Lcaron", "\u013d"},
        {"lcaron", "\u013e"},
        {"Lcedil", "\u013b"},
        {"lcedil", "\u013c"},
        {"lceil", "\u2308"},
        {"lcub", "\u007b"},
        {"Lcy", "\u041b"},
        {"lcy", "\u043b"},
        {"ldca", "\u2936"},
        {"ldquo", "\u201c"},
        {"ldquor", "\u201e"},
        {"ldrdhar", "\u2967"},
        {"ldrushar", "\u294b"},
        {"ldsh", "\u21b2"},
        {"lE", "\u2266"},
        {"le", "\u2264"},
        {"LeftAngleBracket", "\u27e8"},
        {"LeftArrow", "\u2190"},
        {"Leftarrow", "\u21d0"},
        {"leftarrow", "\u2190"},
        {"LeftArrowBar", "\u21e4"},
        {"LeftArrowRightArrow", "\u21c6"},
        {"leftarrowtail", "\u21a2"},
        {"LeftCeiling", "\u2308"},
        {"LeftDoubleBracket", "\u27e6"},
        {"LeftDownTeeVector", "\u2961"},
        {"LeftDownVector", "\u21c3"},
        {"LeftDownVectorBar", "\u2959"},
        {"LeftFloor", "\u230a"},
        {"leftharpoondown", "\u21bd"},
        {"leftharpoonup", "\u21bc"},
        {"leftleftarrows", "\u21c7"},
        {"LeftRightArrow", "\u2194"},
        {"Leftrightarrow", "\u21d4"},
        {"leftrightarrow", "\u2194"},
        {"leftrightarrows", "\u21c6"},
        {"leftrightharpoons", "\u21cb"},
        {"leftrightsquigarrow", "\u21ad"},
        {"LeftRightVector", "\u294e"},
        {"LeftTee", "\u22a3"},
        {"LeftTeeArrow", "\u21a4"},
        {"LeftTeeVector", "\u295a"},
        {"leftthreetimes", "\u22cb"},
        {"LeftTriangle", "\u22b2"},
        {"LeftTriangleBar", "\u29cf"},
        {"LeftTriangleEqual", "\u22b4"},
        {"LeftUpDownVector", "\u2951"},
        {"LeftUpTeeVector", "\u2960"},
        {"LeftUpVector", "\u21bf"},
        {"LeftUpVectorBar", "\u2958"},
        {"LeftVector", "\u21bc"},
        {"LeftVectorBar", "\u2952"},
        {"lEg", "\u2a8b"},
        {"leg", "\u22da"},
        {"leq", "\u2264"},
        {"leqq", "\u2266"},
        {"leqslant", "\u2a7d"},
        {"les", "\u2a7d"},
        {"lescc", "\u2aa8"},
        {"lesdot", "\u2a7f"},
        {"lesdoto", "\u2a81"},
        {"lesdotor", "\u2a83"},
        {"lesg", "\u22da\ufe00"},
        {"lesges", "\u2a93"},
        {"lessapprox", "\u2a85"},
        {"lessdot", "\u22d6"},
        {"lesseqgtr", "\u22da"},
        {"lesseqqgtr", "\u2a8b"},
        {"LessEqualGreater", "\u22da"},
        {"LessFullEqual", "\u2266"},
        {"LessGreater", "\u2276"},
        {"lessgtr", "\u2276"},
        {"LessLess", "\u2aa1"},
        {"lesssim", "\u2272"},
        {"LessSlantEqual", "\u2a7d"},
        {"LessTilde", "\u2272"},
        {"lfisht", "\u297c"},
        {"lfloor", "\u230a"},
        {"Lfr", "\U0001D50F"},
        {"lfr", "\U0001D529"},
        {"lg", "\u2276"},
        {"lgE", "\u2a91"},
        {"lHar", "\u2962"},
        {"lhard", "\u21bd"},
        {"lharu", "\u21bc"},
        {"lharul", "\u296a"},
        {"lhblk", "\u2584"},
        {"LJcy", "\u0409"},
        {"ljcy", "\u0459"},
        {"Ll", "\u22d8"},
        {"ll", "\u226a"},
        {"llarr", "\u21c7"},
        {"llcorner", "\u231e"},
        {"Lleftarrow", "\u21da"},
        {"llhard", "\u296b"},
        {"lltri", "\u25fa"},
        {"Lmidot", "\u013f"},
        {"lmidot", "\u0140"},
        {"lmoust", "\u23b0"},
        {"lmoustache", "\u23b0"},
        {"lnap", "\u2a89"},
        {"lnapprox", "\u2a89"},
        {"lnE", "\u2268"},
        {"lne", "\u2a87"},
        {"lneq", "\u2a87"},
        {"lneqq", "\u2268"},
        {"lnsim", "\u22e6"},
        {"loang", "\u27ec"},
        {"loarr", "\u21fd"},
        {"lobrk", "\u27e6"},
        {"LongLeftArrow", "\u27f5"},
        {"Longleftarrow", "\u27f8"},
        {"longleftarrow", "\u27f5"},
        {"LongLeftRightArrow", "\u27f7"},
        {"Longleftrightarrow", "\u27fa"},
        {"longleftrightarrow", "\u27f7"},
        {"longmapsto", "\u27fc"},
        {"LongRightArrow", "\u27f6"},
        {"Longrightarrow", "\u27f9"},
        {"longrightarrow", "\u27f6"},
        {"looparrowleft", "\u21ab"},
        {"looparrowright", "\u21ac"},
        {"lopar", "\u2985"},
        {"Lopf", "\U0001D543"},
        {"lopf", "\U0001D55D"},
        {"loplus", "\u2a2d"},
        {"lotimes", "\u2a34"},
        {"lowast", "\u2217"},
        {"lowbar", "\u005f"},
        {"LowerLeftArrow", "\u2199"},
        {"LowerRightArrow", "\u2198"},
        {"loz", "\u25ca"},
        {"lozenge", "\u25ca"},
        {"lozf", "\u29eb"},
        {"lpar", "\u0028"},
        {"lparlt", "\u2993"},
        {"lrarr", "\u21c6"},
        {"lrcorner", "\u231f"},
        {"lrhar", "\u21cb"},
        {"lrhard", "\u296d"},
        {"lrm", "\u200e"},
        {"lrtri", "\u22bf"},
        {"lsaquo", "\u2039"},
        {"Lscr", "\u2112"},
        {"lscr", "\U0001D4C1"},
        {"Lsh", "\u21b0"},
        {"lsh", "\u21b0"},
        {"lsim", "\u2272"},
        {"lsime", "\u2a8d"},
        {"lsimg", "\u2a8f"},
        {"lsqb", "\u005b"},
        {"lsquo", "\u2018"},
        {"lsquor", "\u201a"},
        {"Lstrok", "\u0141"},
        {"lstrok", "\u0142"},
        {"LT", "\u003c"},
        {"Lt", "\u226a"},
        {"lt", "\u003c"},
        {"ltcc", "\u2aa6"},
        {"ltcir", "\u2a79"},
        {"ltdot", "\u22d6"},
        {"lthree", "\u22cb"},
        {"ltimes", "\u22c9"},
        {"ltlarr", "\u2976"},
        {"ltquest", "\u2a7b"},
        {"ltri", "\u25c3"},
        {"ltrie", "\u22b4"},
        {"ltrif", "\u25c2"},
        {"ltrPar", "\u2996"},
        {"lurdshar", "\u294a"},
        {"luruhar", "\u2966"},
        {"lvertneqq", "\u2268\ufe00"},
        {"lvnE", "\u2268\ufe00"},
        {"macr", "\u00af"},
        {"male", "\u2642"},
        {"malt", "\u2720"},
        {"maltese", "\u2720"},
        {"Map", "\u2905"},
        {"map", "\u21a6"},
        {"mapsto", "\u21a6"},
        {"mapstodown", "\u21a7"},
        {"mapstoleft", "\u21a4"},
        {"mapstoup", "\u21a5"},
        {"marker", "\u25ae"},
        {"mcomma", "\u2a29"},
        {"Mcy", "\u041c"},
        {"mcy", "\u043c"},
        {"mdash", "\u2014"},
        {"mDDot", "\u223a"},
        {"measuredangle", "\u2221"},
        {"MediumSpace", "\u205f"},
        {"Mellintrf", "\u2133"},
        {"Mfr", "\U0001D510"},
        {"mfr", "\U0001D52A"},
        {"mho", "\u2127"},
        {"micro", "\u00b5"},
        {"mid", "\u2223"},
        {"midast", "\u002a"},
        {"midcir", "\u2af0"},
        {"middot", "\u00b7"},
        {"minus", "\u2212"},
        {"minusb", "\u229f"},
        {"minusd", "\u2238"},
        {"minusdu", "\u2a2a"},
        {"MinusPlus", "\u2213"},
        {"mlcp", "\u2adb"},
        {"mldr", "\u2026"},
        {"mnplus", "\u2213"},
        {"models", "\u22a7"},
        {"Mopf", "\U0001D544"},
        {"mopf", "\U0001D55E"},
        {"mp", "\u2213"},
        {"Mscr", "\u2133"},
        {"mscr", "\U0001D4C2"},
        {"mstpos", "\u223e"},
        {"Mu", "\u039c"},
        {"mu", "\u03bc"},
        {"multimap", "\u22b8"},
        {"mumap", "\u22b8"},
        {"nabla", "\u2207"},
        {"Nacute", "\u0143"},
        {"nacute", "\u0144"},
        {"nang", "\u2220\u20d2"},
        {"nap", "\u2249"},
        {"napE", "\u2a70\u0338"},
        {"napid", "\u224b\u0338"},
        {"napos", "\u0149"},
        {"napprox", "\u2249"},
        {"natur", "\u266e"},
        {"natural", "\u266e"},
        {"naturals", "\u2115"},
        {"nbsp", "\u00a0"},
        {"nbump", "\u224e\u0338"},
        {"nbumpe", "\u224f\u0338"},
        {"ncap", "\u2a43"},
        {"Ncaron", "\u0147"},
        {"ncaron", "\u0148"},
        {"Ncedil", "\u0145"},
        {"ncedil", "\u0146"},
        {"ncong", "\u2247"},
        {"ncongdot", "\u2a6d\u0338"},
        {"ncup", "\u2a42"},
        {"Ncy", "\u041d"},
        {"ncy", "\u043d"},
        {"ndash", "\u2013"},
        {"ne", "\u2260"},
        {"nearhk", "\u2924"},
        {"neArr", "\u21d7"},
        {"nearr", "\u2197"},
        {"nearrow", "\u2197"},
        {"nedot", "\u2250\u0338"},
        {"NegativeMediumSpace", "\u200b"},
        {"NegativeThickSpace", "\u200b"},
        {"NegativeThinSpace", "\u200b"},
        {"NegativeVeryThinSpace", "\u200b"},
        {"nequiv", "\u2262"},
        {"nesear", "\u2928"},
        {"nesim", "\u2242\u0338"},
        {"NestedGreaterGreater", "\u226b"},
        {"NestedLessLess", "\u226a"},
        {"NewLine", "\u000a"},
        {"nexist", "\u2204"},
        {"nexists", "\u2204"},
        {"Nfr", "\U0001D511"},
        {"nfr", "\U0001D52B"},
        {"ngE", "\u2267\u0338"},
        {"nge", "\u2271"},
        {"ngeq", "\u2271"},
        {"ngeqq", "\u2267\u0338"},
        {"ngeqslant", "\u2a7e\u0338"},
        {"nges", "\u2a7e\u0338"},
        {"nGg", "\u22d9\u0338"},
        {"ngsim", "\u2275"},
        {"nGt", "\u226b\u20d2"},
        {"ngt", "\u226f"},
        {"ngtr", "\u226f"},
        {"nGtv", "\u226b\u0338"},
        {"nhArr", "\u21ce"},
        {"nharr", "\u21ae"},
        {"nhpar", "\u2af2"},
        {"ni", "\u220b"},
        {"nis", "\u22fc"},
        {"nisd", "\u22fa"},
        {"niv", "\u220b"},
        {"NJcy", "\u040a"},
        {"njcy", "\u045a"},
        {"nlArr", "\u21cd"},
        {"nlarr", "\u219a"},
        {"nldr", "\u2025"},
        {"nlE", "\u2266\u0338"},
        {"nle", "\u2270"},
        {"nLeftarrow", "\u21cd"},
        {"nleftarrow", "\u219a"},
        {"nLeftrightarrow", "\u21ce"},
        {"nleftrightarrow", "\u21ae"},
        {"nleq", "\u2270"},
        {"nleqq", "\u2266\u0338"},
        {"nleqslant", "\u2a7d\u0338"},
        {"nles", "\u2a7d\u0338"},
        {"nless", "\u226e"},
        {"nLl", "\u22d8\u0338"},
        {"nlsim", "\u2274"},
        {"nLt", "\u226a\u20d2"},
        {"nlt", "\u226e"},
        {"nltri", "\u22ea"},
        {"nltrie", "\u22ec"},
        {"nLtv", "\u226a\u0338"},
        {"nmid", "\u2224"},
        {"NoBreak", "\u2060"},
        {"NonBreakingSpace", "\u00a0"},
        {"Nopf", "\u2115"},
        {"nopf", "\U0001D55F"},
        {"Not", "\u2aec"},
        {"not", "\u00ac"},
        {"NotCongruent", "\u2262"},
        {"NotCupCap", "\u226d"},
        {"NotDoubleVerticalBar", "\u2226"},
        {"NotElement", "\u2209"},
        {"NotEqual", "\u2260"},
        {"NotEqualTilde", "\u2242\u0338"},
        {"NotExists", "\u2204"},
        {"NotGreater", "\u226f"},
        {"NotGreaterEqual", "\u2271"},
        {"NotGreaterFullEqual", "\u2267\u0338"},
        {"NotGreaterGreater", "\u226b\u0338"},
        {"NotGreaterLess", "\u2279"},
        {"NotGreaterSlantEqual", "\u2a7e\u0338"},
        {"NotGreaterTilde", "\u2275"},
        {"NotHumpDownHump", "\u224e\u0338"},
        {"NotHumpEqual", "\u224f\u0338"},
        {"notin", "\u2209"},
        {"notindot", "\u22f5\u0338"},
        {"notinE", "\u22f9\u0338"},
        {"notinva", "\u2209"},
        {"notinvb", "\u22f7"},
        {"notinvc", "\u22f6"},
        {"NotLeftTriangle", "\u22ea"},
        {"NotLeftTriangleBar", "\u29cf\u0338"},
        {"NotLeftTriangleEqual", "\u22ec"},
        {"NotLess", "\u226e"},
        {"NotLessEqual", "\u2270"},
        {"NotLessGreater", "\u2278"},
        {"NotLessLess", "\u226a\u0338"},
        {"NotLessSlantEqual", "\u2a7d\u0338"},
        {"NotLessTilde", "\u2274"},
        {"NotNestedGreaterGreater", "\u2aa2\u0338"},
        {"NotNestedLessLess", "\u2aa1\u0338"},
        {"notni", "\u220c"},
        {"notniva", "\u220c"},
        {"notnivb", "\u22fe"},
        {"notnivc", "\u22fd"},
        {"NotPrecedes", "\u2280"},
        {"NotPrecedesEqual", "\u2aaf\u0338"},
        {"NotPrecedesSlantEqual", "\u22e0"},
        {"NotReverseElement", "\u220c"},
        {"NotRightTriangle", "\u22eb"},
        {"NotRightTriangleBar", "\u29d0\u0338"},
        {"NotRightTriangleEqual", "\u22ed"},
        {"NotSquareSubset", "\u228f\u0338"},
        {"NotSquareSubsetEqual", "\u22e2"},
        {"NotSquareSuperset", "\u2290\u0338"},
        {"NotSquareSupersetEqual", "\u22e3"},
        {"NotSubset", "\u2282\u20d2"},
        {"NotSubsetEqual", "\u2288"},
        {"NotSucceeds", "\u2281"},
        {"NotSucceedsEqual", "\u2ab0\u0338"},
        {"NotSucceedsSlantEqual", "\u22e1"},
        {"NotSucceedsTilde", "\u227f\u0338"},
        {"NotSuperset", "\u2283\u20d2"},
        {"NotSupersetEqual", "\u2289"},
        {"NotTilde", "\u2241"},
        {"NotTildeEqual", "\u2244"},
        {"NotTildeFullEqual", "\u2247"},
        {"NotTildeTilde", "\u2249"},
        {"NotVerticalBar", "\u2224"},
        {"npar", "\u2226"},
        {"nparallel", "\u2226"},
        {"nparsl", "\u2afd\u20e5"},
        {"npart", "\u2202\u0338"},
        {"npolint", "\u2a14"},
        {"npr", "\u2280"},
        {"nprcue", "\u22e0"},
        {"npre", "\u2aaf\u0338"},
        {"nprec", "\u2280"},
        {"npreceq", "\u2aaf\u0338"},
        {"nrArr", "\u21cf"},
        {"nrarr", "\u219b"},
        {"nrarrc", "\u2933\u0338"},
        {"nrarrw", "\u219d\u0338"},
        {"nRightarrow", "\u21cf"},
        {"nrightarrow", "\u219b"},
        {"nrtri", "\u22eb"},
        {"nrtrie", "\u22ed"},
        {"nsc", "\u2281"},
        {"nsccue", "\u22e1"},
        {"nsce", "\u2ab0\u0338"},
        {"Nscr", "\U0001D4A9"},
        {"nscr", "\U0001D4C3"},
        {"nshortmid", "\u2224"},
        {"nshortparallel", "\u2226"},
        {"nsim", "\u2241"},
        {"nsime", "\u2244"},
        {"nsimeq", "\u2244"},
        {"nsmid", "\u2224"},
        {"nspar", "\u2226"},
        {"nsqsube", "\u22e2"},
        {"nsqsupe", "\u22e3"},
        {"nsub", "\u2284"},
        {"nsubE", "\u2ac5\u0338"},
        {"nsube", "\u2288"},
        {"nsubset", "\u2282\u20d2"},
        {"nsubseteq", "\u2288"},
        {"nsubseteqq", "\u2ac5\u0338"},
        {"nsucc", "\u2281"},
        {"nsucceq", "\u2ab0\u0338"},
        {"nsup", "\u2285"},
        {"nsupE", "\u2ac6\u0338"},
        {"nsupe", "\u2289"},
        {"nsupset", "\u2283\u20d2"},
        {"nsupseteq", "\u2289"},
        {"nsupseteqq", "\u2ac6\u0338"},
        {"ntgl", "\u2279"},
        {"Ntilde", "\u00d1"},
        {"ntilde", "\u00f1"},
        {"ntlg", "\u2278"},
        {"ntriangleleft", "\u22ea"},
        {"ntrianglelefteq", "\u22ec"},
        {"ntriangleright", "\u22eb"},
        {"ntrianglerighteq", "\u22ed"},
        {"Nu", "\u039d"},
        {"nu", "\u03bd"},
        {"num", "\u0023"},
        {"numero", "\u2116"},
        {"numsp", "\u2007"},
        {"nvap", "\u224d\u20d2"},
        {"nVDash", "\u22af"},
        {"nVdash", "\u22ae"},
        {"nvDash", "\u22ad"},
        {"nvdash", "\u22ac"},
        {"nvge", "\u2265\u20d2"},
        {"nvgt", "\u003e\u20d2"},
        {"nvHarr", "\u2904"},
        {"nvinfin", "\u29de"},
        {"nvlArr", "\u2902"},
        {"nvle", "\u2264\u20d2"},
        {"nvlt", "\u003c\u20d2"},
        {"nvltrie", "\u22b4\u20d2"},
        {"nvrArr", "\u2903"},
        {"nvrtrie", "\u22b5\u20d2"},
        {"nvsim", "\u223c\u20d2"},
        {"nwarhk", "\u2923"},
        {"nwArr", "\u21d6"},
        {"nwarr", "\u2196"},
        {"nwarrow", "\u2196"},
        {"nwnear", "\u2927"},
        {"Oacute", "\u00d3"},
        {"oacute", "\u00f3"},
        {"oast", "\u229b"},
        {"ocir", "\u229a"},
        {"Ocirc", "\u00d4"},
        {"ocirc", "\u00f4"},
        {"Ocy", "\u041e"},
        {"ocy", "\u043e"},
        {"odash", "\u229d"},
        {"Odblac", "\u0150"},
        {"odblac", "\u0151"},
        {"odiv", "\u2a38"},
        {"odot", "\u2299"},
        {"odsold", "\u29bc"},
        {"OElig", "\u0152"},
        {"oelig", "\u0153"},
        {"ofcir", "\u29bf"},
        {"Ofr", "\U0001D512"},
        {"ofr", "\U0001D52C"},
        {"ogon", "\u02db"},
        {"Ograve", "\u00d2"},
        {"ograve", "\u00f2"},
        {"ogt", "\u29c1"},
        {"ohbar", "\u29b5"},
        {"ohm", "\u03a9"},
        {"oint", "\u222e"},
        {"olarr", "\u21ba"},
        {"olcir", "\u29be"},
        {"olcross", "\u29bb"},
        {"oline", "\u203e"},
        {"olt", "\u29c0"},
        {"Omacr", "\u014c"},
        {"omacr", "\u014d"},
        {"Omega", "\u03a9"},
        {"omega", "\u03c9"},
        {"Omicron", "\u039f"},
        {"omicron", "\u03bf"},
        {"omid", "\u29b6"},
        {"ominus", "\u2296"},
        {"Oopf", "\U0001D546"},
        {"oopf", "\U0001D560"},
        {"opar", "\u29b7"},
        {"OpenCurlyDoubleQuote", "\u201c"},
        {"OpenCurlyQuote", "\u2018"},
        {"operp", "\u29b9"},
        {"oplus", "\u2295"},
        {"Or", "\u2a54"},
        {"or", "\u2228"},
        {"orarr", "\u21bb"},
        {"ord", "\u2a5d"},
        {"order", "\u2134"},
        {"orderof", "\u2134"},
        {"ordf", "\u00aa"},
        {"ordm", "\u00ba"},
        {"origof", "\u22b6"},
        {"oror", "\u2a56"},
        {"orslope", "\u2a57"},
        {"orv", "\u2a5b"},
        {"oS", "\u24c8"},
        {"Oscr", "\U0001D4AA"},
        {"oscr", "\u2134"},
        {"Oslash", "\u00d8"},
        {"oslash", "\u00f8"},
        {"osol", "\u2298"},
        {"Otilde", "\u00d5"},
        {"otilde", "\u00f5"},
        {"Otimes", "\u2a37"},
        {"otimes", "\u2297"},
        {"otimesas", "\u2a36"},
        {"Ouml", "\u00d6"},
        {"ouml", "\u00f6"},
        {"ovbar", "\u233d"},
        {"OverBar", "\u203e"},
        {"OverBrace", "\u23de"},
        {"OverBracket", "\u23b4"},
        {"OverParenthesis", "\u23dc"},
        {"par", "\u2225"},
        {"para", "\u00b6"},
        {"parallel", "\u2225"},
        {"parsim", "\u2af3"},
        {"parsl", "\u2afd"},
        {"part", "\u2202"},
        {"PartialD", "\u2202"},
        {"Pcy", "\u041f"},
        {"pcy", "\u043f"},
        {"percnt", "\u0025"},
        {"period", "\u002e"},
        {"permil", "\u2030"},
        {"perp", "\u22a5"},
        {"pertenk", "\u2031"},
        {"Pfr", "\U0001D513"},
        {"pfr", "\U0001D52D"},
        {"Phi", "\u03a6"},
        {"phi", "\u03c6"},
        {"phiv", "\u03d5"},
        {"phmmat", "\u2133"},
        {"phone", "\u260e"},
        {"Pi", "\u03a0"},
        {"pi", "\u03c0"},
        {"pitchfork", "\u22d4"},
        {"piv", "\u03d6"},
        {"planck", "\u210f"},
        {"planckh", "\u210e"},
        {"plankv", "\u210f"},
        {"plus", "\u002b"},
        {"plusacir", "\u2a23"},
        {"plusb", "\u229e"},
        {"pluscir", "\u2a22"},
        {"plusdo", "\u2214"},
        {"plusdu", "\u2a25"},
        {"pluse", "\u2a72"},
        {"PlusMinus", "\u00b1"},
        {"plusmn", "\u00b1"},
        {"plussim", "\u2a26"},
        {"plustwo", "\u2a27"},
        {"pm", "\u00b1"},
        {"Poincareplane", "\u210c"},
        {"pointint", "\u2a15"},
        {"Popf", "\u2119"},
        {"popf", "\U0001D561"},
        {"pound", "\u00a3"},
        {"Pr", "\u2abb"},
        {"pr", "\u227a"},
        {"prap", "\u2ab7"},
        {"prcue", "\u227c"},
        {"prE", "\u2ab3"},
        {"pre", "\u2aaf"},
        {"prec", "\u227a"},
        {"precapprox", "\u2ab7"},
        {"preccurlyeq", "\u227c"},
        {"Precedes", "\u227a"},
        {"PrecedesEqual", "\u2aaf"},
        {"PrecedesSlantEqual", "\u227c"},
        {"PrecedesTilde", "\u227e"},
        {"preceq", "\u2aaf"},
        {"precnapprox", "\u2ab9"},
        {"precneqq", "\u2ab5"},
        {"precnsim", "\u22e8"},
        {"precsim", "\u227e"},
        {"Prime", "\u2033"},
        {"prime", "\u2032"},
        {"primes", "\u2119"},
        {"prnap", "\u2ab9"},
        {"prnE", "\u2ab5"},
        {"prnsim", "\u22e8"},
        {"prod", "\u220f"},
        {"Product", "\u220f"},
        {"profalar", "\u232e"},
        {"profline", "\u2312"},
        {"profsurf", "\u2313"},
        {"prop", "\u221d"},
        {"Proportion", "\u2237"},
        {"Proportional", "\u221d"},
        {"propto", "\u221d"},
        {"prsim", "\u227e"},
        {"prurel", "\u22b0"},
        {"Pscr", "\U0001D4AB"},
        {"pscr", "\U0001D4C5"},
        {"Psi", "\u03a8"},
        {"psi", "\u03c8"},
        {"puncsp", "\u2008"},
        {"Qfr", "\U0001D514"},
        {"qfr", "\U0001D52E"},
        {"qint", "\u2a0c"},
        {"Qopf", "\u211a"},
        {"qopf", "\U0001D562"},
        {"qprime", "\u2057"},
        {"Qscr", "\U0001D4AC"},
        {"qscr", "\U0001D4C6"},
        {"quaternions", "\u210d"},
        {"quatint", "\u2a16"},
        {"quest", "\u003f"},
        {"questeq", "\u225f"},
        {"QUOT", "\u0022"},
        {"quot", "\u0022"},
        {"rAarr", "\u21db"},
        {"race", "\u223d\u0331"},
        {"Racute", "\u0154"},
        {"racute", "\u0155"},
        {"radic", "\u221a"},
        {"raemptyv", "\u29b3"},
        {"Rang", "\u27eb"},
        {"rang", "\u27e9"},
        {"rangd", "\u2992"},
        {"range", "\u29a5"},
        {"rangle", "\u27e9"},
        {"raquo", "\u00bb"},
        {"Rarr", "\u21a0"},
        {"rArr", "\u21d2"},
        {"rarr", "\u2192"},
        {"rarrap", "\u2975"},
        {"rarrb", "\u21e5"},
        {"rarrbfs", "\u2920"},
        {"rarrc", "\u2933"},
        {"rarrfs", "\u291e"},
        {"rarrhk", "\u21aa"},
        {"rarrlp", "\u21ac"},
        {"rarrpl", "\u2945"},
        {"rarrsim", "\u2974"},
        {"Rarrtl", "\u2916"},
        {"rarrtl", "\u21a3"},
        {"rarrw", "\u219d"},
        {"rAtail", "\u291c"},
        {"ratail", "\u291a"},
        {"ratio", "\u2236"},
        {"rationals", "\u211a"},
        {"RBarr", "\u2910"},
        {"rBarr", "\u290f"},
        {"rbarr", "\u290d"},
        {"rbbrk", "\u2773"},
        {"rbrace", "\u007d"},
        {"rbrack", "\u005d"},
        {"rbrke", "\u298c"},
        {"rbrksld", "\u298e"},
        {"rbrkslu", "\u2990"},
        {"Rcaron", "\u0158"},
        {"rcaron", "\u0159"},
        {"Rcedil", "\u0156"},
        {"rcedil", "\u0157"},
        {"rceil", "\u2309"},
        {"rcub", "\u007d"},
        {"Rcy", "\u0420"},
        {"rcy", "\u0440"},
        {"rdca", "\u2937"},
        {"rdldhar", "\u2969"},
        {"rdquo", "\u201d"},
        {"rdquor", "\u201d"},
        {"rdsh", "\u21b3"},
        {"Re", "\u211c"},
        {"real", "\u211c"},
        {"realine", "\u211b"},
        {"realpart", "\u211c"},
        {"reals", "\u211d"},
        {"rect", "\u25ad"},
        {"REG", "\u00ae"},
        {"reg", "\u00ae"},
        {"ReverseElement", "\u220b"},
        {"ReverseEquilibrium", "\u21cb"},
        {"ReverseUpEquilibrium", "\u296f"},
        {"rfisht", "\u297d"},
        {"rfloor", "\u230b"},
        {"Rfr", "\u211c"},
        {"rfr", "\U0001D52F"},
        {"rHar", "\u2964"},
        {"rhard", "\u21c1"},
        {"rharu", "\u21c0"},
        {"rharul", "\u296c"},
        {"Rho", "\u03a1"},
        {"rho", "\u03c1"},
        {"rhov", "\u03f1"},
        {"RightAngleBracket", "\u27e9"},
        {"RightArrow", "\u2192"},
        {"Rightarrow", "\u21d2"},
        {"rightarrow", "\u2192"},
        {"RightArrowBar", "\u21e5"},
        {"RightArrowLeftArrow", "\u21c4"},
        {"rightarrowtail", "\u21a3"},
        {"RightCeiling", "\u2309"},
        {"RightDoubleBracket", "\u27e7"},
        {"RightDownTeeVector", "\u295d"},
        {"RightDownVector", "\u21c2"},
        {"RightDownVectorBar", "\u2955"},
        {"RightFloor", "\u230b"},
        {"rightharpoondown", "\u21c1"},
        {"rightharpoonup", "\u21c0"},
        {"rightleftarrows", "\u21c4"},
        {"rightleftharpoons", "\u21cc"},
        {"rightrightarrows", "\u21c9"},
        {"rightsquigarrow", "\u219d"},
        {"RightTee", "\u22a2"},
        {"RightTeeArrow", "\u21a6"},
        {"RightTeeVector", "\u295b"},
        {"rightthreetimes", "\u22cc"},
        {"RightTriangle", "\u22b3"},
        {"RightTriangleBar", "\u29d0"},
        {"RightTriangleEqual", "\u22b5"},
        {"RightUpDownVector", "\u294f"},
        {"RightUpTeeVector", "\u295c"},
        {"RightUpVector", "\u21be"},
        {"RightUpVectorBar", "\u2954"},
        {"RightVector", "\u21c0"},
        {"RightVectorBar", "\u2953"},
        {"ring", "\u02da"},
        {"risingdotseq", "\u2253"},
        {"rlarr", "\u21c4"},
        {"rlhar", "\u21cc"},
        {"rlm", "\u200f"},
        {"rmoust", "\u23b1"},
        {"rmoustache", "\u23b1"},
        {"rnmid", "\u2aee"},
        {"roang", "\u27ed"},
        {"roarr", "\u21fe"},
        {"robrk", "\u27e7"},
        {"ropar", "\u2986"},
        {"Ropf", "\u211d"},
        {"ropf", "\U0001D563"},
        {"roplus", "\u2a2e"},
        {"rotimes", "\u2a35"},
        {"RoundImplies", "\u2970"},
        {"rpar", "\u0029"},
        {"rpargt", "\u2994"},
        {"rppolint", "\u2a12"},
        {"rrarr", "\u21c9"},
        {"Rrightarrow", "\u21db"},
        {"rsaquo", "\u203a"},
        {"Rscr", "\u211b"},
        {"rscr", "\U0001D4C7"},
        {"Rsh", "\u21b1"},
        {"rsh", "\u21b1"},
        {"rsqb", "\u005d"},
        {"rsquo", "\u2019"},
        {"rsquor", "\u2019"},
        {"rthree", "\u22cc"},
        {"rtimes", "\u22ca"},
        {"rtri", "\u25b9"},
        {"rtrie", "\u22b5"},
        {"rtrif", "\u25b8"},
        {"rtriltri", "\u29ce"},
        {"RuleDelayed", "\u29f4"},
        {"ruluhar", "\u2968"},
        {"rx", "\u211e"},
        {"Sacute", "\u015a"},
        {"sacute", "\u015b"},
        {"sbquo", "\u201a"},
        {"Sc", "\u2abc"},
        {"sc", "\u227b"},
        {"scap", "\u2ab8"},
        {"Scaron", "\u0160"},
        {"scaron", "\u0161"},
        {"sccue", "\u227d"},
        {"scE", "\u2ab4"},
        {"sce", "\u2ab0"},
        {"Scedil", "\u015e"},
        {"scedil", "\u015f"},
        {"Scirc", "\u015c"},
        {"scirc", "\u015d"},
        {"scnap", "\u2aba"},
        {"scnE", "\u2ab6"},
        {"scnsim", "\u22e9"},
        {"scpolint", "\u2a13"},
        {"scsim", "\u227f"},
        {"Scy", "\u0421"},
        {"scy", "\u0441"},
        {"sdot", "\u22c5"},
        {"sdotb", "\u22a1"},
        {"sdote", "\u2a66"},
        {"searhk", "\u2925"},
        {"seArr", "\u21d8"},
        {"searr", "\u2198"},
        {"searrow", "\u2198"},
        {"sect", "\u00a7"},
        {"semi", "\u003b"},
        {"seswar", "\u2929"},
        {"setminus", "\u2216"},
        {"setmn", "\u2216"},
        {"sext", "\u2736"},
        {"Sfr", "\U0001D516"},
        {"sfr", "\U0001D530"},
        {"sfrown", "\u2322"},
        {"sharp", "\u266f"},
        {"SHCHcy", "\u0429"},
        {"shchcy", "\u0449"},
        {"SHcy", "\u0428"},
        {"shcy", "\u0448"},
        {"ShortDownArrow", "\u2193"},
        {"ShortLeftArrow", "\u2190"},
        {"shortmid", "\u2223"},
        {"shortparallel", "\u2225"},
        {"ShortRightArrow", "\u2192"},
        {"ShortUpArrow", "\u2191"},
        {"shy", "\u00ad"},
        {"Sigma", "\u03a3"},
        {"sigma", "\u03c3"},
        {"sigmaf", "\u03c2"},
        {"sigmav", "\u03c2"},
        {"sim", "\u223c"},
        {"simdot", "\u2a6a"},
        {"sime", "\u2243"},
        {"simeq", "\u2243"},
        {"simg", "\u2a9e"},
        {"simgE", "\u2aa0"},
        {"siml", "\u2a9d"},
        {"simlE", "\u2a9f"},
        {"simne", "\u2246"},
        {"simplus", "\u2a24"},
        {"simrarr", "\u2972"},
        {"slarr", "\u2190"},
        {"SmallCircle", "\u2218"},
        {"smallsetminus", "\u2216"},
        {"smashp", "\u2a33"},
        {"smeparsl", "\u29e4"},
        {"smid", "\u2223"},
        {"smile", "\u2323"},
        {"smt", "\u2aaa"},
        {"smte", "\u2aac"},
        {"smtes", "\u2aac\ufe00"},
        {"SOFTcy", "\u042c"},
        {"softcy", "\u044c"},
        {"sol", "\u002f"},
        {"solb", "\u29c4"},
        {"solbar", "\u233f"},
        {"Sopf", "\U0001D54A"},
        {"sopf", "\U0001D564"},
        {"spades", "\u2660"},
        {"spadesuit", "\u2660"},
        {"spar", "\u2225"},
        {"sqcap", "\u2293"},
        {"sqcaps", "\u2293\ufe00"},
        {"sqcup", "\u2294"},
        {"sqcups", "\u2294\ufe00"},
        {"Sqrt", "\u221a"},
        {"sqsub", "\u228f"},
        {"sqsube", "\u2291"},
        {"sqsubset", "\u228f"},
        {"sqsubseteq", "\u2291"},
        {"sqsup", "\u2290"},
        {"sqsupe", "\u2292"},
        {"sqsupset", "\u2290"},
        {"sqsupseteq", "\u2292"},
        {"squ", "\u25a1"},
        {"Square", "\u25a1"},
        {"square", "\u25a1"},
        {"SquareIntersection", "\u2293"},
        {"SquareSubset", "\u228f"},
        {"SquareSubsetEqual", "\u2291"},
        {"SquareSuperset", "\u2290"},
        {"SquareSupersetEqual", "\u2292"},
        {"SquareUnion", "\u2294"},
        {"squarf", "\u25aa"},
        {"squf", "\u25aa"},
        {"srarr", "\u2192"},
        {"Sscr", "\U0001D4AE"},
        {"sscr", "\U0001D4C8"},
        {"ssetmn", "\u2216"},
        {"ssmile", "\u2323"},
        {"sstarf", "\u22c6"},
        {"Star", "\u22c6"},
        {"star", "\u2606"},
        {"starf", "\u2605"},
        {"straightepsilon", "\u03f5"},
        {"straightphi", "\u03d5"},
        {"strns", "\u00af"},
        {"Sub", "\u22d0"},
        {"sub", "\u2282"},
        {"subdot", "\u2abd"},
        {"subE", "\u2ac5"},
        {"sube", "\u2286"},
        {"subedot", "\u2ac3"},
        {"submult", "\u2ac1"},
        {"subnE", "\u2acb"},
        {"subne", "\u228a"},
        {"subplus", "\u2abf"},
        {"subrarr", "\u2979"},
        {"Subset", "\u22d0"},
        {"subset", "\u2282"},
        {"subseteq", "\u2286"},
        {"subseteqq", "\u2ac5"},
        {"SubsetEqual", "\u2286"},
        {"subsetneq", "\u228a"},
        {"subsetneqq", "\u2acb"},
        {"subsim", "\u2ac7"},
        {"subsub", "\u2ad5"},
        {"subsup", "\u2ad3"},
        {"succ", "\u227b"},
        {"succapprox", "\u2ab8"},
        {"succcurlyeq", "\u227d"},
        {"Succeeds", "\u227b"},
        {"SucceedsEqual", "\u2ab0"},
        {"SucceedsSlantEqual", "\u227d"},
        {"SucceedsTilde", "\u227f"},
        {"succeq", "\u2ab0"},
        {"succnapprox", "\u2aba"},
        {"succneqq", "\u2ab6"},
        {"succnsim", "\u22e9"},
        {"succsim", "\u227f"},
        {"SuchThat", "\u220b"},
        {"Sum", "\u2211"},
        {"sum", "\u2211"},
        {"sung", "\u266a"},
        {"Sup", "\u22d1"},
        {"sup", "\u2283"},
        {"sup1", "\u00b9"},
        {"sup2", "\u00b2"},
        {"sup3", "\u00b3"},
        {"supdot", "\u2abe"},
        {"supdsub", "\u2ad8"},
        {"supE", "\u2ac6"},
        {"supe", "\u2287"},
        {"supedot", "\u2ac4"},
        {"Superset", "\u2283"},
        {"SupersetEqual", "\u2287"},
        {"suphsol", "\u27c9"},
        {"suphsub", "\u2ad7"},
        {"suplarr", "\u297b"},
        {"supmult", "\u2ac2"},
        {"supnE", "\u2acc"},
        {"supne", "\u228b"},
        {"supplus", "\u2ac0"},
        {"Supset", "\u22d1"},
        {"supset", "\u2283"},
        {"supseteq", "\u2287"},
        {"supseteqq", "\u2ac6"},
        {"supsetneq", "\u228b"},
        {"supsetneqq", "\u2acc"},
        {"supsim", "\u2ac8"},
        {"supsub", "\u2ad4"},
        {"supsup", "\u2ad6"},
        {"swarhk", "\u2926"},
        {"swArr", "\u21d9"},
        {"swarr", "\u2199"},
        {"swarrow", "\u2199"},
        {"swnwar", "\u292a"},
        {"szlig", "\u00df"},
        {"Tab", "\u0009"},
        {"target", "\u2316"},
        {"Tau", "\u03a4"},
        {"tau", "\u03c4"},
        {"tbrk", "\u23b4"},
        {"Tcaron", "\u0164"},
        {"tcaron", "\u0165"},
        {"Tcedil", "\u0162"},
        {"tcedil", "\u0163"},
        {"Tcy", "\u0422"},
        {"tcy", "\u0442"},
        {"tdot", "\u20db"},
        {"telrec", "\u2315"},
        {"Tfr", "\U0001D517"},
        {"tfr", "\U0001D531"},
        {"there4", "\u2234"},
        {"Therefore", "\u2234"},
        {"therefore", "\u2234"},
        {"Theta", "\u0398"},
        {"theta", "\u03b8"},
        {"thetasym", "\u03d1"},
        {"thetav", "\u03d1"},
        {"thickapprox", "\u2248"},
        {"thicksim", "\u223c"},
        {"ThickSpace", "\u205f\u200a"},
        {"thinsp", "\u2009"},
        {"ThinSpace", "\u2009"},
        {"thkap", "\u2248"},
        {"thksim", "\u223c"},
        {"THORN", "\u00de"},
        {"thorn", "\u00fe"},
        {"Tilde", "\u223c"},
        {"tilde", "\u02dc"},
        {"TildeEqual", "\u2243"},
        {"TildeFullEqual", "\u2245"},
        {"TildeTilde", "\u2248"},
        {"times", "\u00d7"},
        {"timesb", "\u22a0"},
        {"timesbar", "\u2a31"},
        {"timesd", "\u2a30"},
        {"tint", "\u222d"},
        {"toea", "\u2928"},
        {"top", "\u22a4"},
        {"topbot", "\u2336"},
        {"topcir", "\u2af1"},
        {"Topf", "\U0001D54B"},
        {"topf", "\U0001D565"},
        {"topfork", "\u2ada"},
        {"tosa", "\u2929"},
        {"tprime", "\u2034"},
        {"TRADE", "\u2122"},
        {"trade", "\u2122"},
        {"triangle", "\u25b5"},
        {"triangledown", "\u25bf"},
        {"triangleleft", "\u25c3"},
        {"trianglelefteq", "\u22b4"},
        {"triangleq", "\u225c"},
        {"triangleright", "\u25b9"},
        {"trianglerighteq", "\u22b5"},
        {"tridot", "\u25ec"},
        {"trie", "\u225c"},
        {"triminus", "\u2a3a"},
        {"TripleDot", "\u20db"},
        {"triplus", "\u2a39"},
        {"trisb", "\u29cd"},
        {"tritime", "\u2a3b"},
        {"trpezium", "\u23e2"},
        {"Tscr", "\U0001D4AF"},
        {"tscr", "\U0001D4C9"},
        {"TScy", "\u0426"},
        {"tscy", "\u0446"},
        {"TSHcy", "\u040b"},
        {"tshcy", "\u045b"},
        {"Tstrok", "\u0166"},
        {"tstrok", "\u0167"},
        {"twixt", "\u226c"},
        {"twoheadleftarrow", "\u219e"},
        {"twoheadrightarrow", "\u21a0"},
        {"Uacute", "\u00da"},
        {"uacute", "\u00fa"},
        {"Uarr", "\u219f"},
        {"uArr", "\u21d1"},
        {"uarr", "\u2191"},
        {"Uarrocir", "\u2949"},
        {"Ubrcy", "\u040e"},
        {"ubrcy", "\u045e"},
        {"Ubreve", "\u016c"},
        {"ubreve", "\u016d"},
        {"Ucirc", "\u00db"},
        {"ucirc", "\u00fb"},
        {"Ucy", "\u0423"},
        {"ucy", "\u0443"},
        {"udarr", "\u21c5"},
        {"Udblac", "\u0170"},
        {"udblac", "\u0171"},
        {"udhar", "\u296e"},
        {"ufisht", "\u297e"},
        {"Ufr", "\U0001D518"},
        {"ufr", "\U0001D532"},
        {"Ugrave", "\u00d9"},
        {"ugrave", "\u00f9"},
        {"uHar", "\u2963"},
        {"uharl", "\u21bf"},
        {"uharr", "\u21be"},
        {"uhblk", "\u2580"},
        {"ulcorn", "\u231c"},
        {"ulcorner", "\u231c"},
        {"ulcrop", "\u230f"},
        {"ultri", "\u25f8"},
        {"Umacr", "\u016a"},
        {"umacr", "\u016b"},
        {"uml", "\u00a8"},
        {"UnderBar", "\u005f"},
        {"UnderBrace", "\u23df"},
        {"UnderBracket", "\u23b5"},
        {"UnderParenthesis", "\u23dd"},
        {"Union", "\u22c3"},
        {"UnionPlus", "\u228e"},
        {"Uogon", "\u0172"},
        {"uogon", "\u0173"},
        {"Uopf", "\U0001D54C"},
        {"uopf", "\U0001D566"},
        {"UpArrow", "\u2191"},
        {"Uparrow", "\u21d1"},
        {"uparrow", "\u2191"},
        {"UpArrowBar", "\u2912"},
        {"UpArrowDownArrow", "\u21c5"},
        {"UpDownArrow", "\u2195"},
        {"Updownarrow", "\u21d5"},
        {"updownarrow", "\u2195"},
        {"UpEquilibrium", "\u296e"},
        {"upharpoonleft", "\u21bf"},
        {"upharpoonright", "\u21be"},
        {"uplus", "\u228e"},
        {"UpperLeftArrow", "\u2196"},
        {"UpperRightArrow", "\u2197"},
        {"Upsi", "\u03d2"},
        {"upsi", "\u03c5"},
        {"upsih", "\u03d2"},
        {"Upsilon", "\u03a5"},
        {"upsilon", "\u03c5"},
        {"UpTee", "\u22a5"},
        {"UpTeeArrow", "\u21a5"},
        {"upuparrows", "\u21c8"},
        {"urcorn", "\u231d"},
        {"urcorner", "\u231d"},
        {"urcrop", "\u230e"},
        {"Uring", "\u016e"},
        {"uring", "\u016f"},
        {"urtri", "\u25f9"},
        {"Uscr", "\U0001D4B0"},
        {"uscr", "\U0001D4CA"},
        {"utdot", "\u22f0"},
        {"Utilde", "\u0168"},
        {"utilde", "\u0169"},
        {"utri", "\u25b5"},
        {"utrif", "\u25b4"},
        {"uuarr", "\u21c8"},
        {"Uuml", "\u00dc"},
        {"uuml", "\u00fc"},
        {"uwangle", "\u29a7"},
        {"vangrt", "\u299c"},
        {"varepsilon", "\u03f5"},
        {"varkappa", "\u03f0"},
        {"varnothing", "\u2205"},
        {"varphi", "\u03d5"},
        {"varpi", "\u03d6"},
        {"varpropto", "\u221d"},
        {"vArr", "\u21d5"},
        {"varr", "\u2195"},
        {"varrho", "\u03f1"},
        {"varsigma", "\u03c2"},
        {"varsubsetneq", "\u228a\ufe00"},
        {"varsubsetneqq", "\u2acb\ufe00"},
        {"varsupsetneq", "\u228b\ufe00"},
        {"varsupsetneqq", "\u2acc\ufe00"},
        {"vartheta", "\u03d1"},
        {"vartriangleleft", "\u22b2"},
        {"vartriangleright", "\u22b3"},
        {"Vbar", "\u2aeb"},
        {"vBar", "\u2ae8"},
        {"vBarv", "\u2ae9"},
        {"Vcy", "\u0412"},
        {"vcy", "\u0432"},
        {"VDash", "\u22ab"},
        {"Vdash", "\u22a9"},
        {"vDash", "\u22a8"},
        {"vdash", "\u22a2"},
        {"Vdashl", "\u2ae6"},
        {"Vee", "\u22c1"},
        {"vee", "\u2228"},
        {"veebar", "\u22bb"},
        {"veeeq", "\u225a"},
        {"vellip", "\u22ee"},
        {"Verbar", "\u2016"},
        {"verbar", "\u007c"},
        {"Vert", "\u2016"},
        {"vert", "\u007c"},
        {"VerticalBar", "\u2223"},
        {"VerticalLine", "\u007c"},
        {"VerticalSeparator", "\u2758"},
        {"VerticalTilde", "\u2240"},
        {"VeryThinSpace", "\u200a"},
        {"Vfr", "\U0001D519"},
        {"vfr", "\U0001D533"},
        {"vltri", "\u22b2"},
        {"vnsub", "\u2282\u20d2"},
        {"vnsup", "\u2283\u20d2"},
        {"Vopf", "\U0001D54D"},
        {"vopf", "\U0001D567"},
        {"vprop", "\u221d"},
        {"vrtri", "\u22b3"},
        {"Vscr", "\U0001D4B1"},
        {"vscr", "\U0001D4CB"},
        {"vsubnE", "\u2acb\ufe00"},
        {"vsubne", "\u228a\ufe00"},
        {"vsupnE", "\u2acc\ufe00"},
        {"vsupne", "\u228b\ufe00"},
        {"Vvdash", "\u22aa"},
        {"vzigzag", "\u299a"},
        {"Wcirc", "\u0174"},
        {"wcirc", "\u0175"},
        {"wedbar", "\u2a5f"},
        {"Wedge", "\u22c0"},
        {"wedge", "\u2227"},
        {"wedgeq", "\u2259"},
        {"weierp", "\u2118"},
        {"Wfr", "\U0001D51A"},
        {"wfr", "\U0001D534"},
        {"Wopf", "\U0001D54E"},
        {"wopf", "\U0001D568"},
        {"wp", "\u2118"},
        {"wr", "\u2240"},
        {"wreath", "\u2240"},
        {"Wscr", "\U0001D4B2"},
        {"wscr", "\U0001D4CC"},
        {"xcap", "\u22c2"},
        {"xcirc", "\u25ef"},
        {"xcup", "\u22c3"},
        {"xdtri", "\u25bd"},
        {"Xfr", "\U0001D51B"},
        {"xfr", "\U0001D535"},
        {"xhArr", "\u27fa"},
        {"xharr", "\u27f7"},
        {"Xi", "\u039e"},
        {"xi", "\u03be"},
        {"xlArr", "\u27f8"},
        {"xlarr", "\u27f5"},
        {"xmap", "\u27fc"},
        {"xnis", "\u22fb"},
        {"xodot", "\u2a00"},
        {"Xopf", "\U0001D54F"},
        {"xopf", "\U0001D569"},
        {"xoplus", "\u2a01"},
        {"xotime", "\u2a02"},
        {"xrArr", "\u27f9"},
        {"xrarr", "\u27f6"},
        {"Xscr", "\U0001D4B3"},
        {"xscr", "\U0001D4CD"},
        {"xsqcup", "\u2a06"},
        {"xuplus", "\u2a04"},
        {"xutri", "\u25b3"},
        {"xvee", "\u22c1"},
        {"xwedge", "\u22c0"},
        {"Yacute", "\u00dd"},
        {"yacute", "\u00fd"},
        {"YAcy", "\u042f"},
        {"yacy", "\u044f"},
        {"Ycirc", "\u0176"},
        {"ycirc", "\u0177"},
        {"Ycy", "\u042b"},
        {"ycy", "\u044b"},
        {"yen", "\u00a5"},
        {"Yfr", "\U0001D51C"},
        {"yfr", "\U0001D536"},
        {"YIcy", "\u0407"},
        {"yicy", "\u0457"},
        {"Yopf", "\U0001D550"},
        {"yopf", "\U0001D56A"},
        {"Yscr", "\U0001D4B4"},
        {"yscr", "\U0001D4CE"},
        {"YUcy", "\u042e"},
        {"yucy", "\u044e"},
        {"Yuml", "\u0178"},
        {"yuml", "\u00ff"},
        {"Zacute", "\u0179"},
        {"zacute", "\u017a"},
        {"Zcaron", "\u017d"},
        {"zcaron", "\u017e"},
        {"Zcy", "\u0417"},
        {"zcy", "\u0437"},
        {"Zdot", "\u017b"},
        {"zdot", "\u017c"},
        {"zeetrf", "\u2128"},
        {"ZeroWidthSpace", "\u200b"},
        {"Zeta", "\u0396"},
        {"zeta", "\u03b6"},
        {"Zfr", "\u2128"},
        {"zfr", "\U0001D537"},
        {"ZHcy", "\u0416"},
        {"zhcy", "\u0436"},
        {"zigrarr", "\u21dd"},
        {"Zopf", "\u2124"},
        {"zopf", "\U0001D56B"},
        {"Zscr", "\U0001D4B5"},
        {"zscr", "\U0001D4CF"},
        {"zwj", "\u200d"},
        {"zwnj", "\u200c"}
    };
    
    // verify if no conversion is needed.
    if(s.empty() || s.find("&") == std::string::npos)
        return s.to_string();
    
    std::ostringstream os;
    
    for(size_t i = 0; i < s.size(); ++i){
        char ch = s[i];
        
        if(ch == '&'){
            size_t ei = s.find_first_not_of(
                "abcdefghijklmnopqrstuvwxyz"
                "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                "0123456789"
                "#",
                i+1
            );
            if(ei != std::string::npos && s[ei] == ';'){
                auto entity = s.substr(i+1, (ei-i)-1).to_string();
                if(entity.size() > 1 && entity[0] == '#'){
                    if(entity[1] == 'x' || entity[1] == 'X')
                        os << (unsigned char)strtol(
                            entity.c_str() + 1,
                            nullptr,
                            16
                        );
                    else
                        os << (unsigned char)strtol(
                            entity.c_str(),
                            nullptr,
                            10
                        );
                    
                    i = ei;
                    continue;
                }else{
                    i = ei;
                    auto it = html_entities.find(entity);
                    if(it == html_entities.end())
                        os << "&" << entity << ";";
                    else
                        os << it->second;
                    continue;
                }
            }
        }
        
        os << ch;
    }
    
    return os.str();
}


inline std::string encode_uri(md::string_view s)
{
    std::ostringstream os;
    
    for(auto c : s){
        if(
            (c >= 'a' && c <= 'z') ||
            (c >= 'A' && c <= 'Z') ||
            (c >= '0' && c <= '9') ||
            c == ';' || c == ',' || c == '/' || c == '?' || c == ':' ||
            c == '@' || c == '&' || c == '=' || c == '+' || c == '$' ||
            c == '-' || c == '_' || c == '.' || c == '!' || c == '~' ||
            c == '*' || c == '\'' || c == '(' || c == ')' || c == '#'
        ){
            os << c;
            continue;
        }
        
        os << "%";
        os << std::uppercase << std::hex << std::setw(2) << (int)c;
    }
    
    return os.str();
}
inline std::string decode_uri(md::string_view s)
{
    std::ostringstream os;
    char t[3]{0,0,0};
    for(size_t i = 0; i < s.size(); ++i){
        if(s[i] == '%' && i < s.size()-2){
            t[0] = *(s.data() +i+1);
            t[1] = *(s.data() +i+2);
            os << (unsigned char)strtol(t, nullptr, 16);
            i += 2;
            continue;
        }
        
        os << s[i];
    }
    
    return os.str();
}
inline std::string encode_uri_component(md::string_view s)
{
    std::ostringstream os;
    
    for(auto c : s){
        if(
            (c >= 'a' && c <= 'z') ||
            (c >= 'A' && c <= 'Z') ||
            (c >= '0' && c <= '9') ||
            c == '-' || c == '_' || c == '.' || c == '!' || c == '~' ||
            c == '*' || c == '\'' || c == '(' || c == ')'
        ){
            os << c;
            continue;
        }
        
        os << "%";
        os << std::uppercase << std::hex << std::setw(2) << (int)c;
    }
    
    return os.str();
}
inline std::string decode_uri_component(md::string_view s)
{
    return decode_uri(s);
}



/* Generate the human-readable hex representation of an apr_uint64_t
* (basically a faster version of 'sprintf("%llx")')
*/
#define HEX_DIGITS "0123456789abcdef"
static char *etag_uint64_to_hex(char *next, uint64_t u)
{
    int printing = 0;
    int shift = sizeof(uint64_t) * 8 - 4;
    do {
        unsigned short next_digit =
            (unsigned short)((u >> shift) & (uint64_t)0xf);
        
        if (next_digit) {
            *next++ = HEX_DIGITS[next_digit];
            printing = 1;
        
        } else if (printing) {
            *next++ = HEX_DIGITS[next_digit];
        }
        
        shift -= 4;
        
    } while (shift);
    
    *next++ = HEX_DIGITS[u & (uint64_t)0xf];
    
    return next;
}

void get_etag(const struct stat& file_stat, std::string& str_etag);
inline void get_etag(const char* filename, std::string& str_etag)
{
    struct stat file_stat;
    stat(filename, &file_stat);
    get_etag(file_stat, str_etag);
}

constexpr size_t CHARS_PER_UINT64 = (sizeof(uint64_t) * 2);
constexpr size_t CHARS_PER_ETAG = (3 * CHARS_PER_UINT64 + 1 + sizeof("--"));

inline void get_etag(const struct stat& file_stat, std::string& str_etag)
{
    //char *etag = new char[3 * CHARS_PER_UINT64 + 1 + sizeof("\"--\"")];
    //char *etag = new char[3 * CHARS_PER_UINT64 + 1 + sizeof("--")];
    char *etag = new char[CHARS_PER_ETAG];
    char *next = etag;

    //*next++ = '"';
    next = etag_uint64_to_hex( next, file_stat.st_ino);
    *next++ = '-';
    next = etag_uint64_to_hex( next, file_stat.st_size);
    *next++ = '-';
    next = etag_uint64_to_hex( next, file_stat.st_mtime);
    //*next++ = '"';
    *next = '\0';
    
    str_etag.append(etag);
    
    delete[] etag;
}



} //ns evmvc

#endif //_boost_beast_mvc_utils_h
